### ISSUE TITLE
setup.sh: line 27: lolcat: command not found figlet: Bloody: Unable to open font file

### ISSUE THREAD

**Issue by vokica** [Crevils/InstaReport#21]
hi, Crevils do u know maybe solution fo this problem?

**Comment by baff3r** [comment]
I have this error too

**Comment by harsh7839** [comment]
Hii I can fix this error..
1. Go to the InstaReport File.
2. edit the setup.sh file using nano or other editing app, replace all Bloody words with word 'standard', and  replace all the python word with python3.
3. Save the file and then run it.
4.For fix lolcat error use 'pip install lolcat' command
5.And Finally Run the script.

**Comment by ejazabbas73** [comment]
> # Solution
> Hii I can fix this error..
> 
> 1. Go to the InstaReport File.
> 2. edit the setup.sh file using nano or other editing app, replace all Bloody words with word 'standard', and  replace all the python word with python3.
> 3. Save the file and then run it.
> 
> 4.For fix lolcat error use
> 
> ```shell
> pip install lolcat
> ```
> 
> 5.And Finally Run the script.

still getting error please fix it

**Comment by Crevils** [comment]
fixed this issue, go through readme for more info
