### ISSUE TITLE
how can we fix this error please help!!

### ISSUE THREAD

**Issue by shendejagrut** [Crevils/InstaReport#23]
while running ReportBot.py
setup.sh: line 15: lolcat: command not found
setup.sh: line 27: lolcat: command not found
figlet: Bloody: Unable to open font file

**Comment by ansuh0260** [comment]
> while running ReportBot.py setup.sh: line 15: lolcat: command not found setup.sh: line 27: lolcat: command not found figlet: Bloody: Unable to open font file

Same error is get for me also

**Comment by Crevils** [comment]
fixed this issue, go through readme for more info
