### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ThSubZer0** [Crevils/InstaReport#25]
Guys every time I try to start the installation it shows me this error "Package 'python' has no installation candidate", what is the problem? 
![image](https://user-images.githubusercontent.com/104060457/168383477-4a93919a-a6f8-427e-9ee2-fd82d0405ef4.jpeg)

**Comment by harsh7839** [comment]
Bro There is no python, Always use python3..
And Don't need to run setup.sh.
Simply use command python3 ReportBot.py

**Comment by ThSubZer0** [comment]
How can I use it?

**Comment by harsh7i** [comment]
> How can I use it?

Hello @ThSubZer0 
Always use python3 instead of python.
* For example
    * `sudo apt install python3`
    *  `python3 ReportBot.py`

**Comment by harsh7i** [comment]
> How can I use it?

Hello @ThSubZer0 
Always use python3 instead of python.
* For example
    * `sudo apt install python3`
    *  `python3 ReportBot.py`

**Comment by Crevils** [comment]
fixed this issue, go through readme for more info
