### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by rohaan-gh** [Crevils/InstaReport#27]
when I run it with python3 ReportBot.py It shows the following error:
![Screenshot_20220608-025924.png](https://user-images.githubusercontent.com/96631138/172490310-f0bb880b-d53c-40ff-9624-e64cd4380712.png)

**Comment by rohaan-gh** [comment]
![Screenshot_20220608-025924.png](https://user-images.githubusercontent.com/96631138/172490371-107d94d9-69dd-4ab4-b570-4c6670df6a67.png)

**Comment by Crevils** [comment]
fixed this issue, go through readme for more info
