### ISSUE TITLE
Start error 

### ISSUE THREAD

**Issue by ankitpatidar0** [Crevils/InstaReport#28]
![Screenshot_2022-06-12-00-36-51-38_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/75633199/173201636-229fdfa1-e28c-4818-9e3f-26df1810ad44.jpg)
Please help what I do for this error ..?

**Comment by vikashere96** [comment]
Did you got any solutions?

**Comment by Crevils** [comment]
fixed this issue, go through readme for more info
