### ISSUE TITLE
Proxybroker install package problem ???

### ISSUE THREAD

**Issue by haszimoto** [Crevils/InstaReport#30]
This tool not see my proxybroker.

Always see this information:

"[-] 'proxybroker' package not installed!                                  
[*] Type 'pip install proxybroker' to install!" 

but i installed ??? any idea how to fix ?

Kali linux

**Comment by Tomkhalifa** [comment]
Same problem in termux plz help

**Comment by Tomkhalifa** [comment]
![Uploading Screenshot_2023-01-05-22-43-42-713_com.termux.jpg…]()
