### ISSUE TITLE
SyntaxError: invalid syntax. File "ReportBot.py", line 33,50 Propably credentials problem                               

### ISSUE THREAD

**Issue by haszimoto** [Crevils/InstaReport#32]
File "ReportBot.py", line 33                                                        
    cred =credentials .Certificate ({"type":"service_account","project_id":f"{os.getenv('PRODUCT_ID')}","private_key_id":f"{os.getenv('PRIVATE_KEY_ID')}","private_key":"-----BEGIN PRIVATE KEY-----\......(Private Key is Here)\n-----END PRIVATE KEY-----\n","client_email":f"{os.getenv('CLIENT_EMAIL')}","client_id":f"{os.getenv('CLIENT_ID')}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":f"{os.getenv('CLIENT_URL')}"})#line:50      
                                                                                                      ^                                                                     
SyntaxError: invalid syntax  

Any idea how to fix ?

**Comment by Crevils** [comment]
fixed this issue, go through readme for more info
