### ISSUE TITLE
No module named 'firebase_admin'

### ISSUE THREAD

**Issue by vikashere96** [Crevils/InstaReport#39]
![Screenshot_20220811-141007_Termux](https://user-images.githubusercontent.com/97658526/184095996-6a66c5e3-111c-4fe4-833e-28f693b60364.jpg)

Can anyone got the solution?

**Comment by tanishkbhati** [comment]
You got solution? @vikashere96

**Comment by ardadasdelen** [comment]
pip install firebase_admin

**Comment by Crevils** [comment]
fixed this issue, go through readme for more info
