### ISSUE TITLE
Bad magic number in .pyc file

### ISSUE THREAD

**Issue by Official-Husko** [Crevils/InstaReport#4]
All requirements installed but i get "Bad magic number in .pyc file" when i run it with python ReportBot.pyc

**Comment by Crevils** [comment]
which os you are using?
Make sure you have python version of 3 or above

**Comment by NoelJacob** [comment]
It happens in Windows

**Comment by Official-Husko** [comment]
> 
> 
> which os you are using?
> Make sure you have python version of 3 or above

Im using windows 10 and im running the latest python version

**Comment by savioazure** [comment]
i had the same issue on ubuntu 20.04.. didnt wknow why will be...

**Comment by Teknival** [comment]
Same on Kali Brow's 👍🏻

**Comment by Teknival** [comment]
> 
> 
> > which os you are using?
> > Make sure you have python version of 3 or above
> 
> Im using windows 10 and im running the latest python version

-----------

I'm gonna try on win 10, i reply if its work 💯

**Comment by gratv** [comment]
Same issue on Windows 10, with Python 3 and Git installed

**Comment by stasiia708** [comment]
same issue here
Using win 10 and python latest version.

anyone find a solutions?

**Comment by mastermind-20** [comment]
Same Problem in Termux I have everything update python version 3.9 but then also not working

**Comment by afzalahammed** [comment]
I tried in Kali,Termux & in Windows same issue

**Comment by dara-want-fuck-kurdistan** [comment]
Same issue on gcloud shell app on iphone

**Comment by mxwo93** [comment]
same issue here. windows 10 and kali

**Comment by mxwo93** [comment]
it's because it's compiled and each version of python has its own specific magic number. there are probably a few people who have the exact python version, but until the author replies - no one can use it..

**Comment by Crevils** [comment]
Fixed the issue of bad magic
Try 
`
python ReportBot.py
`
Instead of python ReportBot.pyc
