### ISSUE TITLE
No module named 'colorama'

### ISSUE THREAD

**Issue by RaghulSeeliyur** [Crevils/InstaReport#45]
Need a help to fix this 

![Screenshot_2022-11-15-11-34-37-06_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/82638516/201838877-ce94476b-e906-4797-8987-6595c56774aa.jpg)

![Screenshot_2022-11-15-11-34-08-96_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/82638516/201839108-695b29d6-dab5-433a-a393-bf7c430cb047.jpg)

**Comment by Whitereaper97** [comment]
You have to type pip install colorama

**Comment by raj9140** [comment]
Ha ye problem mujhe bhi ayi hai

**Comment by Crevils** [comment]
fixed this issue, you can go through readme for more info
