### ISSUE TITLE
Re-upload this 👇

### ISSUE THREAD

**Issue by yezz123** [Crevils/InstaReport#5]
`RuntimeError: Bad magic number in .pyc file`
- You need to give the runner code not the version of debug dude that can't work not the same process and not the same Runtime.
Re-check your code and then post it cause that will never work if he stay in debug version with ext `.pyc`.  
![Screenshot 2020-11-10 005445](https://user-images.githubusercontent.com/52716203/98610251-7d523600-22ef-11eb-9293-30d9aa4a29f8.png)

**Comment by Crevils** [comment]
hey, lets have a discussion on telegram. DM me on telegram at t.me/crevilbot
