### ISSUE TITLE
Modified

### ISSUE THREAD

**Issue by myselfsoz** [Crevils/InstaReport#50]
not working 
![image](https://user-images.githubusercontent.com/121366571/212556341-5763ec5a-1053-4870-982a-fa975dac145d.png)

**Comment by Kashifalipro** [comment]
I need insta reporting commands I want to banned someone insta account

**Comment by 0x5b9** [comment]
this error is caused by the use of poor proxies. High quality proxies are required for the use of this tool

**Comment by Crevils** [comment]
fixed
