### ISSUE TITLE
Instagram baning 

### ISSUE THREAD

**Issue by Darkpop1** [Crevils/InstaReport#52]

**Comment by Garettbillk** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost account ,message him on telegram his telegram username is https://t.me/Blackhathacker11

**Comment by Chetansonkar** [comment]
Mere ko gali deta hai aur live per bhi

**Comment by Zbibi12** [comment]
Please how

**Comment by Chetansonkar** [comment]
Hi sir

**Comment by 5tarLx** [comment]
Can someone tell me how to ban someone's Instagram account? please

**Comment by Crevils** [comment]
updated the script, follow readme
